services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT-11434}:11434"
    environment:
      - OLLAMA_ORIGINS=*
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama_api_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull ${OLLAMA_MODEL:-qwen3.5:2b} &&
      wait
      "

volumes:
  ollama_api_data:
